version: '3'
services:
  bank-api:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      server.error.include-message: always
      spring.datasource.url: 'jdbc:mysql://{URL}:3306/bank'
      spring.datasource.username: {USER}
      spring.datasource.password: {PASSWORD}
    ports:
      - '8080:8080'
    command: mvn spring-boot:run
