version: '3'
services:
  mysqlbank:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'bank'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    networks:
      net:
  bank-api:
    depends_on:
      - mysqlbank
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      server.error.include-message: always
#      spring.datasource.url: 'jdbc:mysql://sistema-monitoramento.comzh9adefdo.us-east-1.rds.amazonaws.com:3306/bank'
#      spring.datasource.username: 'administrador'
#      spring.datasource.password: '***********'
      spring.datasource.url: 'jdbc:mysql://mysqlbank:3306/bank?allowPublicKeyRetrieval=true&useSSL=false'
      spring.datasource.username: 'root'
      spring.datasource.password: 'password'
    ports:
      - '8080:8080'
    command: mvn spring-boot:run
    networks:
      net:
networks:
  net:
    driver: bridge
