version: '3'
services:
  bank-api:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      server.error.include-message: always
      spring.datasource.url: 'jdbc:mysql://sistema-monitoramento.comzh9adefdo.us-east-1.rds.amazonaws.com:3306/bank'
      spring.datasource.username: 'administrador'
      spring.datasource.password: 'HNjd48TGnuwSkfU2023!'
    ports:
      - '8080:8080'
    command: mvn spring-boot:run